- name: "Make sure /opt exists"
  file: path=/opt state=directory mode=0755 owner=root group=root

- name: Check if mailhog binary exists
  stat: path=/opt/mailhog
  check_mode: false
  register: register_mailhog_binary

- name: Get Mailhog version
  shell: '/opt/mailhog --version | sed "s/MailHog version: //"'
  changed_when: false
  check_mode: false
  register: register_mailhog_version
  when: register_mailhog_binary.stat.exists

- name: "Download binary"
  get_url:
    url: https://github.com/mailhog/MailHog/releases/download/v{{ mailhog_version }}/MailHog_linux_amd64
    dest: /opt/mailhog
    mode: 0755
    force: yes
  when: not register_mailhog_binary.stat.exists or register_mailhog_version.stdout is version(mailhog_version, 'ne')
  notify:
    - restart mailhog

- name: Mailhog vhost
  template: src=nginx.conf-template.j2 dest=/etc/nginx/sites-enabled/mailhog.{{ wsl_domain_ending }}.conf
  notify: reload nginx

- name: Install mailhog.service unit file
  template: src=mailhog.service.j2 dest=/etc/systemd/system/mailhog.service

- name: Ensure mailhog is started and enabled on boot.
  service: name=mailhog state=started enabled=true daemon_reload=yes
