- name: initial items to install services properly
  hosts: localhost
  connection: local
  become: true
  gather_subset: '!hardware'

  vars:
    - supported_distros: ['Ubuntu']
    - supported_releases: ['focal', 'jammy']

  pre_tasks:
    - name: Fail on not supported distros
      fail:
        msg: "{{ ansible_distribution }} is not in supported distros list: {{ supported_distros|join(', ') }}"
      when: ansible_distribution not in supported_distros

    - name: Fail on not supported distro releases
      fail:
        msg: "{{ ansible_distribution_release }} is not in supported releases list: {{ supported_releases|join(', ') }}"
      when: ansible_distribution_release not in supported_releases

  vars_files:
    - [ "vars/setup.yml.dist" ] #always load dist in case of missing entries in vars/setup.yml
    - [ "vars/setup.yml", "vars/setup.yml.dist" ] # fallback to .dist

  roles:
    - { role: initial, tags: initial }
