- name: apply common configuration
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/basic.yml
    - vars/mailhog.yml
    - vars/mysql.yml
    - vars/pma.yml

  roles:
    - { role: basic, tags: basic }
    - { role: nginx, tags: nginx }
    - { role: mailhog, tags: mailhog }
    - { role: mariadb, tags: mysql,mariadb }
    - { role: php, tags: php }
    - { role: phpmyadmin, tags: pma }
    - { role: geerlingguy.composer, vars: { composer_version_branch: '', composer_version: '1.10.19', composer_path: /usr/local/bin/composer }, tags: composer }
    - { role: geerlingguy.composer, vars: { composer_version: '2.0.8', composer_path: /usr/local/bin/composer2 }, tags: composer }
    - { role: redis, tags: redis }
    - { role: andrelohmann.wkhtmltopdf, vars: { wkhtmltopdf_install_google_fonts: True } }
