- name: apply web
  hosts: localhost
  connection: local
  become: true
  gather_subset: '!hardware'

  vars_files:
    - [ "vars/setup.yml.dist" ] #always load dist in case of missing entries in vars/setup.yml
    - [ "vars/setup.yml", "vars/setup.yml.dist" ] # fallback to .dist

  roles:
    - { role: common, tags: common }
    - { role: web/nodejs, tags: nodejs }
    - { role: web/wpcli, tags: wpcli }
    - { role: web/yarn, tags: yarn }
    - { role: web/nginx, tags: nginx }
    - { role: web/mailhog, tags: mailhog }
    - { role: web/redis, tags: redis }
    - { role: web/mariadb, tags: mysql,mariadb }
    - { role: web/php, tags: php }
    - { role: web/phpmyadmin, tags: pma }

    - { role: web/phpstorm, tags: phpstorm }
