- name: Add systemd-genie key
  ansible.builtin.apt_key:
    url: https://arkane-systems.github.io/wsl-transdebian/apt/wsl-transdebian.gpg
    keyring: /usr/share/keyrings/systemd-archive-keyring.gpg

- name: Add systemd-genie repository (except hirsute)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/systemd-archive-keyring.gpg] https://arkane-systems.github.io/wsl-transdebian/apt/ {{ ansible_distribution_release }} main"
    filename: "systemd-genie"
  when: ansible_distribution_release != 'hirsute'

- name: Add systemd-genie repository (hirsute)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/systemd-archive-keyring.gpg] https://arkane-systems.github.io/wsl-transdebian/apt/ focal main"
    filename: "systemd-genie"
  when: ansible_distribution_release == 'hirsute'

- name: Install systemd-genie
  apt:
    name: systemd-genie
    state: present

- name: Setup default target
  file:
    src: /usr/lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link

- name: Smaller timeout in default genie setup
  lineinfile:
    path: /etc/genie.ini
    regexp: '^systemd-timeout='
    line: 'systemd-timeout=30'
