# Install required microsoft packages

- name: Add microsoft key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: present

- name: Add microsoft repository (Ubuntu 20.04 / 21.04) # TODO: fix when 21.04 available
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
    filename: microsoft
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release in ['hirsute', 'focal']

- name: Add microsoft repository (Debian)
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main
    filename: microsoft
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- apt:
    name:
      - daemonize
      - dotnet-runtime-5.0
      - systemd-container
