# Setup startup service that setups IP on each launch
- name: "Make sure /opt exists"
  file: path=/opt state=directory mode=0755 owner=root group=root

- name: "Install startup.sh"
  template:
    src: opt.startup.sh.j2
    dest: "/opt/startup.sh"
    owner: root
    group: root
    mode: 0700

- name: Install startup.service unit file
  template: src=etc.systemd.startup.service.j2 dest=/etc/systemd/system/startup.service

- name: Force reload and restart
  ansible.builtin.systemd:
    daemon_reload: yes
    state: restarted
    name: startup
