- name: Install packages required by various tools
  apt:
    name:
      - acl
      - curl
      - gnupg
      - sudo
      - ssh
      - apt-transport-https
    state: present

- name: Install user defined packages
  apt:
    name: "{{ user_packages }}"
    state: present
