- name: Install packages required by various os
  apt:
    name:
      - acl
      - curl
      - gnupg
      - sudo
      - ssh
      - apt-transport-https
    state: present

#- name: Install fallback packages for Jammy
#  apt:
#    deb: "{{ item }}"
#  with_items:
#    - http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.12_amd64.deb
#    - http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu67_67.1-7ubuntu1_amd64.deb
#    - http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.49+dfsg-2ubuntu1.8_amd64.deb
#    - http://archive.ubuntu.com/ubuntu/pool/main/libw/libwebp/libwebp6_0.6.1-2.1_amd64.deb
#  when: ansible_distribution_release == 'jammy'
