- name: Add wsl user
  user:
    name: "{{ wsl_username }}"
    shell: /bin/bash

- name: Allow {{ wsl_username }} to sudo
  template:
    src: etc.sudoers.d.user.j2
    dest: /etc/sudoers.d/{{ wsl_username }}
    owner: root
    group: root
    mode: '0440'
    backup: no
    validate: '/usr/sbin/visudo -cf %s'

# When you run wsl command on windows - you will be logged in genie bottle (systemd calls allowed)
- name: Setup genie for {{ wsl_username }}
  blockinfile:
    create: yes
    path: /home/{{ wsl_username }}/.bashrc
    marker: "# {mark} ANSIBLE BLOCK - GENIE"
    block: |
      if [[ -v SSH_CLIENT ]]; then
        TMPFILE=$(mktemp)
        systemctl show-environment | awk '{print "export "$0}' >> $TMPFILE
        source $TMPFILE
        rm $TMPFILE
      fi

      if [[ ! -v INSIDE_GENIE ]]; then
        exec /usr/bin/genie -c bash -l
      else
        echo -e "\e[92m * Safely within bottle.\e[39m"
      fi
  become_user: "{{ wsl_username }}"