- name: Touch a .hushlogin
  ansible.builtin.file:
    path: /root/.hushlogin
    owner: root
    group: root
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Add wsl user
  user:
    name: "{{ wsl_username }}"
    shell: /bin/bash

- name: Allow {{ wsl_username }} to sudo
  template:
    src: etc.sudoers.d.user.j2
    dest: /etc/sudoers.d/{{ wsl_username }}
    owner: root
    group: root
    mode: '0440'
    backup: no
    validate: '/usr/sbin/visudo -cf %s'

# When you run wsl command on windows - you will be logged in genie bottle (systemd calls allowed)
- name: Setup genie for {{ wsl_username }}
  blockinfile:
    create: yes
    path: /home/{{ wsl_username }}/.bashrc
    marker: "# {mark} ANSIBLE BLOCK - GENIE"
    block: |
      if [[ -v SSH_CLIENT ]]; then
        source <(systemctl show-environment | awk '{print "export "$0}')
      fi

      if [[ ! -v INSIDE_GENIE ]]; then
        exec /usr/bin/genie -c `getent passwd $LOGNAME | cut -d: -f7`
        #exec /usr/bin/genie -c bash -l
      fi
  become_user: "{{ wsl_username }}"

- name: Uncomment colorful terminal in .bashrc
  lineinfile:
    path: /home/{{ wsl_username }}/.bashrc
    regexp: '^#force_color_prompt=(yes|no)'
    line: 'force_color_prompt=yes'
  become_user: "{{ wsl_username }}"

- name: Touch a .hushlogin
  file:
    path: /home/{{ wsl_username }}/.hushlogin
    state: touch
    modification_time: preserve
    access_time: preserve
  become_user: "{{ wsl_username }}"
