- name: Add /etc/wsl.conf
  template: src=templates/wsl.conf-template.j2 dest=/etc/wsl.conf mode=0644

- name: Setup IP Addr
  command: "ip addr add 192.168.50.16/24 broadcast 192.168.50.255 dev eth0 label eth0:1"
  ignore_errors: yes
  failed_when: false
  changed_when: false
  check_mode: no

- name: Install aptitude
  apt: name=aptitude state=present

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade APT to the latest packages
  apt: upgrade=safe

- name: Install packages
  apt:
    state: present
    name:
      - acl
      - ssh
   
- name: Ensure SSH is started and enabled on boot.
  service: name=ssh state=started enabled=true

- name: Check if /etc/ssh/ssh_host_ed25519_key exists
  stat: path=/etc/ssh/ssh_host_ed25519_key
  register: sshkey

- name: create ssh host keys
  command: "ssh-keygen -A"
  when: not sshkey.stat.exists

- name: Allow {{ wsl_username }} to sudo
  template:
    src: sudoers-template.j2
    dest: /etc/sudoers.d/{{ wsl_username }}
    owner: root
    group: root
    mode: '0440'
    backup: no
    validate: '/usr/sbin/visudo -cf %s'

- name: Add authorized key for {{ wsl_username }}
  authorized_key:
    user: "{{ wsl_username }}"
    key: "{{ wsl_public_key }}"

- name: Add /etc/rc.local file for startup
  template: src=templates/rc.local-template.j2 dest=/etc/rc.local mode=0700

- name: Add /etc/resolv.conf
  template: src=templates/resolv.conf-template.j2 dest=/etc/resolv.conf mode=0644

- git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"
  become_user: "{{ wsl_username }}"

- git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  become_user: "{{ wsl_username }}"

- name: "Install aliases"
  template:
    src: bash_aliases.sh
    dest: "/home/{{ wsl_username }}/.bash_aliases"

- name: Setup DISPLAY variable for vcxsrv
  lineinfile:
    path: "/home/{{ wsl_username }}/.bashrc"
    regexp: '^export DISPLAY='
    line: 'export DISPLAY=192.168.50.88:0'