- git_config:
    name: user.name
    scope: global
    value: "{{ git_username }}"
  become_user: "{{ wsl_username }}"

- git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  become_user: "{{ wsl_username }}"