- include: debian.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'focal'


- name: "generate main password hash"
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem

- file: path=/etc/nginx/sites-enabled/default state=absent

- file: path=/var/www/html state=absent

- name: Ensure nginx is started and enabled on boot.
  service: name=nginx state=started enabled=true