- name: Add repository for nginx-mainline (Ubuntu Focal)
  apt_repository:
    repo: 'ppa:ondrej/nginx-mainline'
    filename: nginx
  when: ansible_distribution_release in ['focal']

- name: Add repository for nginx-mainline (Ubuntu jammy)
  block:
    - name: Try jammy codename
      apt_repository:
        repo: 'ppa:ondrej/nginx-mainline'
        filename: nginx
  rescue:
    - name: Jammy repository missing. Fallback to impish
      apt_repository:
        repo: 'ppa:ondrej/nginx-mainline'
        codename: impish
        filename: nginx
  when: ansible_distribution_release in ['jammy']

- name: Install nginx
  apt: name=nginx-full
