- name: Download gpg key
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4f4ea0aae5267a6c
    dest: /usr/share/keyrings/nginx.gpg_armored

- name: De-Armor GPG key
  ansible.builtin.shell: gpg --dearmor < /usr/share/keyrings/nginx.gpg_armored > /usr/share/keyrings/nginx.gpg
  args:
    creates: /usr/share/keyrings/nginx.gpg

- name: Add deb repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx.gpg] https://ppa.launchpadcontent.net/ondrej/nginx/ubuntu {{ ansible_distribution_release }} main"
    filename: "nginx"

- name: Add deb-src repository
  ansible.builtin.apt_repository:
    repo: "deb-src [signed-by=/usr/share/keyrings/nginx.gpg] https://ppa.launchpadcontent.net/ondrej/nginx/ubuntu {{ ansible_distribution_release }} main"
    filename: "nginx"

- name: Install nginx-full
  ansible.builtin.apt:
    name:
      - nginx-full
