- name: Add nginx key
  ansible.builtin.apt_key:
    id: "4f4ea0aae5267a6c"
    keyserver: keyserver.ubuntu.com
    keyring: /usr/share/keyrings/nginx-archive-keyring.gpg

- name: Add repository for nginx-mainline (Ubuntu {{ ansible_distribution_release }})
  block:
    - name: Try {{ ansible_distribution_release }} codename
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://ppa.launchpadcontent.net/ondrej/nginx-mainline/ubuntu {{ ansible_distribution_release }} main"
        filename: "nginx"
  rescue:
    - name: "{{ ansible_distribution_release }} repository missing. Fallback to impish"
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://ppa.launchpadcontent.net/ondrej/nginx-mainline/ubuntu impish main"
        filename: "nginx"
      when: ansible_distribution_release in ['jammy']

    - fail:
        msg: "No fallback for: {{ ansible_distribution_release }}"
      when: ansible_distribution_release not in ['jammy']

- name: Install nginx
  apt: name=nginx-full
