- name: Add nginx key (Ubuntu)
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: present

- name: Add repository for nginx-mainline (Ubuntu)
  apt_repository: repo='ppa:ondrej/nginx-mainline'

- name: Install nginx
  apt: name=nginx-full