# ssh.service - fix
- name: Check if /etc/ssh/ssh_host_ed25519_key exists
  ansible.builtin.stat: path=/etc/ssh/ssh_host_ed25519_key
  register: sshkey

- name: Create ssh host keys
  ansible.builtin.command: "ssh-keygen -A"
  when: not sshkey.stat.exists


# systemd-sysusers.service - fix
- name: Create systemd-sysusers directory
  file: path=/etc/systemd/system/systemd-sysusers.service.d/ state=directory

- name: Edit overrides for systemd-sysusers
  ansible.builtin.copy:
    content: |
      [Service]
      LoadCredential=
    dest: /etc/systemd/system/systemd-sysusers.service.d/override.conf

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

# fixes curl bug
- name: Disable IPv6 DNS lookup
  ansible.builtin.lineinfile:
    dest: /etc/gai.conf
    line: "precedence ::ffff:0:0/96  100"
    state: present
    create: yes
    backup: yes
