- include_tasks: ubuntu.yml

- name: Get installed php versions
  no_log: True
  failed_when: false
  changed_when: false
  check_mode: false
  shell: 'update-alternatives --list php | sed "s/\/usr\/bin\/php//"'
  register: installed_php_versions

- set_fact:
    installed_php_versions: "{{ installed_php_versions.stdout_lines }}"
    php_versions: "{{ php_versions|map('string') }}"

- name: Delete not required versions
  include_tasks: uninstall.yml
  when: "php_version not in php_versions|map('string')"
  loop: "{{ installed_php_versions }}"
  loop_control:
    loop_var: php_version

- name: Install required PHP versions
  include_tasks: install.yml
  loop: "{{ php_versions }}"
  loop_control:
    loop_var: php_version

- name: Select PHP {{ php_default_version }} version selected
  alternatives:
    name: php
    path: /usr/bin/php{{ php_default_version }}

- name: "Make sure /var/www/tools/php exists"
  file: path=/var/www/tools/php state=directory mode=0755 owner=root group=root

- name: Add phpinfo index script
  action: template src=templates/index.php-template.j2 dest=/var/www/tools/php/index.php mode=0755

- name: Add phpinfo script
  action: template src=templates/phpinfo.php-template.j2 dest=/var/www/tools/php/phpinfo.php mode=0755

- name: Install phpinfo vhosts
  action: template src=templates/php-version-nginx.conf-template.j2 dest=/etc/nginx/sites-enabled/phpinfo.{{ wsl_domain_ending }}.conf
  notify: reload nginx
