- name:  Add repository for PHP versions (Ubuntu {{ ansible_distribution_release }})
  apt_repository:
    repo: 'ppa:ondrej/php'
    filename: php
  when: ansible_distribution_release in ['focal', 'jammy']
