- name: Add repository for PHP versions (Ubuntu {{ ansible_distribution_release }})
  block:
    - name: Try {{ ansible_distribution_release }} codename
      apt_repository:
        repo: 'ppa:ondrej/php'
        filename: php
    - apt:
        name:
          - php7.4
          - php8.0
          - php8.1
  rescue:
    - name: Jammy repository missing. Fallback to impish
      apt_repository:
        repo: 'ppa:ondrej/php'
        codename: focal
        filename: php
      when: ansible_distribution_release in ['jammy']

    - fail:
        msg: "No fallback for: {{ ansible_distribution_release }}"
      when: ansible_distribution_release not in ['jammy']
